savebackconfig: true
configversion:
  notify: true
  created: 727
  saved: 727
logging:
  active: true
  debug: false
  backend:
    console:
      active: true
      prefix: '&cAC> &7 '
    file:
      active: true
      prefix: ''
      filename: anticheat.log
    ingamechat:
      active: true
      prefix: '&cAC> &7'
      subscriptions: false
data:
  expiration:
    active: false
    duration: 0
    history: false
  consistencychecks:
    active: true
    interval: 10
    maxtime: 2
    suppresswarnings: false
protection:
  plugins:
    hide:
      active: true
      nopermission:
        message: '&6No Authorization'
        commands:
        - plugins
        - version
        - icanhasbukkit
      unknowncommand:
        message: Unknown command. Type "/help" for help.
        commands: []
  commands:
    consoleonly:
      active: true
      message: '&6 [!] &eDenied. Use CONSOLE to execute this command'
      commands:
      - op
      - deop
  clients:
    motd:
      active: true
      allowall: false
checks:
  blockbreak:
    direction:
      active: true
      actions: cancel vl>10 log:bdirection:0:5:if cancel
    fastbreak:
      active: true
      strict: true
      delay: 100
      intervalsurvival: 100
      grace: 2000
      actions: cancel vl>0 log:fastbreak:3:5:cif cancel
    frequency:
      active: true
      intervalcreative: 95
      intervalsurvival: 45
      shortterm:
        ticks: 5
        limit: 7
      actions: cancel vl>5 log:bbfrequency:3:5:if cancel vl>60 log:bbfrequency:0:5:cif cancel
    noswing:
      active: true
      actions: cancel vl>10 log:noswing:0:5:if cancel
    reach:
      active: true
      actions: cancel vl>5 log:breach:0:2:if cancel
    wrongblock:
      active: false
      level: 10
      actions: cancel vl>10 log:bwrong:0:5:if cancel vl>30 log:bwrong:0:5:cif cancel
  blockinteract:
    direction:
      active: false
      actions: cancel vl>10 log:bdirection:0:3:if cancel
    reach:
      active: false
      actions: cancel vl>5 log:breach:0:2:if cancel
    speed:
      active: true
      interval: 2000
      limit: 60
      actions: cancel vl>200 log:bspeed:0:2:if cancel vl>1000 cancel log:bspeed:0:2:icf
    visible:
      active: true
      actions: cancel vl>100 log:bvisible:0:10:if cancel
  blockplace:
    against:
      active: true
      actions: cancel
    autosign:
      active: true
      actions: cancel vl>10 log:bautosign:0:3:if cancel
    direction:
      active: true
      actions: cancel vl>10 log:bdirection:0:3:if cancel
    fastplace:
      active: true
      limit: 22
      shortterm:
        ticks: 10
        limit: 6
      actions: cancel vl>100 log:fastplace:3:5:cif cancel
    reach:
      active: true
      actions: cancel vl>5 log:breach:0:2:if cancel
    noswing:
      active: true
      exceptions:
      - WATER_LILY
      - FLINT_AND_STEEL
      actions: cancel vl>10 log:noswing:0:5:if cancel
    speed:
      active: true
      interval: 45
      actions: cancel vl>150 log:bpspeed:3:5:if cancel vl>1000 log:bpspeed:3:5:cif cancel
  chat:
    color:
      active: false
      actions: log:color:0:1:if cancel
    commands:
      active: false
      exclusions: []
      handleaschat:
      - me
      level: 10
      shortterm:
        ticks: 18
        level: 3
      actions: log:commands:0:5:cf cancel vl>20 log:commands:0:5:cf cancel
    captcha:
      active: false
      characters: abcdefghjkmnpqrtuvwxyzABCDEFGHJKMNPQRTUVWXYZ2346789
      length: 6
      question: '&cPlease type ''&6[captcha]&c'' to continue sending messages/commands.'
      success: '&aOK, it sounds like you''re not a spambot.'
      tries: 3
      actions: cancel cmd:kickcaptcha vl>4 log:captcha:2:5:cf cancel cmd:kickcaptcha
    text:
      active: true
      allowvlreset: true
      frequency:
        normal:
          minimum: 0.0
          factor: 0.9
          weight: 6
          level: 160
          actions: cancel cmd:tellchatnormal vl>7 log:chatnormal:0:5:f cancel cmd:tellchatnormal vl>20 log:chatnormal:0:5:cf cancel cmd:warnchatnormal vl>40 log:chatnormal:0:5:cf cancel cmd:warnchatnormal
        shortterm:
          minimum: 2.0
          factor: 0.7
          weight: 3.0
          level: 20.0
          actions: log:chatfast:0:5:cf cancel cmd:warnchatfast vl>20 log:chatfast:0:5:cf cancel cmd:kickchat1 vl>40 log:chatfast:0:5:cf cancel cmd:kickchat5
      message:
        lettercount: 1.0
        partition: 1.0
        uppercase: 1.0
        afterjoin: 1.5
        nomoving: 1.5
        repeatviolation: 1.0
        repeatglobal: 1.0
        repeatself: 1.5
        words:
          lengthav: 1.0
          lengthmsg: 1.0
          noletter: 0.0
      global:
        active: true
        weight: 1.0
        words:
          active: false
        prefixes:
          active: false
        similarity:
          active: false
      player:
        active: true
        words:
          active: false
        prefixes:
          active: false
        similarity:
          active: false
    warning:
      active: true
      level: 67
      message: |-
        &e>>>
        &e>>> &cPlease slow down chat, you might get kicked for spam.
        &e>>>
      timeout: 10
    relog:
      active: false
      timeout: 5000
      warning:
        message: '&cYou relogged really fast! If you keep doing that, you''re going to be banned.'
        number: 1
        timeout: 60000
      kickmessage: Too fast re-login, try with a little delay.
      actions: log:relog:0:10:cf cancel vl>20 log:relog:0:10:cf cancel cmd:tempkick5
    logins:
      active: false
      startupdelay: 600
      perworldcount: false
      seconds: 10
      limit: 10
      kickmessage: Too many people logging in, retry soon.
  combined:
    bedleave:
      active: false
      actions: cancel log:bedleave:0:5:if cmd:kickbedleave
    enderpearl:
      active: true
      preventclickblock: true
    improbable:
      active: false
      level: 300
      actions: cancel log:improbable:2:8:if
    invulnerable:
      active: false
      triggers:
        always: false
        falldistance: false
      initialticks:
        join: -1
      ignore:
      - FALL
      modifiers:
        all: 0
    munchhausen:
      active: false
      actions: cancel vl>100 cancel log:munchhausen:0:60:if
    yawrate:
      rate: 380
      penalty:
        factor: 1.0
        minimum: 250
        maximum: 2000
      improbable: false
  fight:
    canceldead: true
    toolchangepenalty: 500
    yawrate:
      active: false
    angle:
      active: true
      threshold: 50
      actions: cancel vl>100 log:angle:3:5:f cancel vl>250 log:angle:0:5:cif cancel
    critical:
      active: false
      falldistance: 0.06251
      velocity: 0.1
      actions: cancel vl>50 log:critical:0:5:cif cancel
    direction:
      active: false
      strict: true
      penalty: 500
      actions: cancel vl>5 log:fdirection:3:5:f cancel vl>20 log:fdirection:0:5:if cancel vl>50 log:fdirection:0:5:cif cancel
    fastheal:
      active: true
      interval: 4000
      buffer: 1000
      actions: cancel vl>10 cancel log:fastheal:0:10:i vl>30 cancel log:fastheal:0:10:if
    godmode:
      active: true
      minage: 1100
      maxage: 5000
      actions: log:godmode:2:5:if cancel vl>60 log:godmode:2:5:icf cancel
    knockback:
      active: false
      interval: 30
      actions: cancel vl>100 log:knockback:0:5:cif cancel
    noswing:
      active: false
      actions: cancel vl>10 log:noswing:0:5:if cancel
    reach:
      active: true
      survivaldistance: 4.4
      penalty: 500
      reduce: true
      reducedistance: 0.9
      reducestep: 0.15
      actions: cancel vl>10 log:freach:2:5:if cancel
    selfhit:
      active: false
      actions: log:fselfhit:0:5:if cancel vl>10 log:fselfhit:0:5:icf cancel cmd:kickselfhit
    speed:
      active: true
      limit: 20
      actions: log:fspeed:0:5:if cancel
      shortterm:
        ticks: 7
        limit: 6
  inventory:
    drop:
      active: false
      limit: 100
      timeframe: 20
      actions: log:drop:0:1:cif cancel cmd:dropkick:0:1
    fastclick:
      active: true
      sparecreative: true
      tweaks1_5: true
      limit:
        shortterm: 4
        normal: 15
      actions: vl>15 log:fastclick:0:5:f cancel
    instantbow:
      active: true
      strict: true
      delay: 200
      actions: vl>50 log:instantbownocancel:0:5:f vl>100 log:instantbow:0:5:cif cancel
    instanteat:
      active: false
      actions: vl>15 log:instanteat:2:5:cif cancel
    fastconsume:
      active: true
      duration: 0.7
      whitelist: false
      items: []
      actions: log:fastconsume:2:5:if cancel
    items:
      active: false
    open:
      active: true
      close: true
      cancelother: true
  moving:
    creativefly:
      active: false
      ignoreallowflight: false
      ignorecreative: false
      horizontalspeed: 100
      maxheight: 128
      verticalspeed: 100
      actions: log:flyshort:3:5:cif cancel vl>100 log:flyshort:0:5:if cancel vl>400 log:flylong:0:5:cif cancel
    morepackets:
      active: true
      seconds: 6
      epsideal: 20
      epsmax: 22
      burst:
        packets: 40
        directviolation: 60
        epmviolation: 180
      actions: log:morepacketsnocancel:2:2:f vl>100 log:morepackets:0:2:f cancel
    morepacketsvehicle:
      active: false
      actions: log:morepackets:2:2:f cancel vl>10 log:morepackets:0:2:f cancel
    nofall:
      active: true
      dealdamage: true
      resetonviolation: false
      resetonteleport: true
      resetonvehicle: true
      anticriticals: true
      actions: cancel vl>5 log:nofall:0:5:if cancel vl>30 log:nofall:0:5:icf cancel
    passable:
      active: false
      raytracing:
        active: true
        blockchangeonly: true
        vcliponly: true
      actions: log:passable:0:5:cif cancel
    survivalfly:
      active: true
      extended:
        vertical-accounting: true
      falldamage: true
      actions: log:flyshort:3:10:f cancel vl>100 log:flyshort:0:10:if cancel vl>400 log:flylong:0:5:cif cancel vl>1500 log:flylong:0:5:cif cancel
      hover:
        active: false
        step: 5
        ticks: 85
        loginticks: 0
        falldamage: true
        sfviolation: 500
    trace:
      size: 60
      mergedist: 0.9752
    vehicles:
      preventdestroyown: true
      enforcelocation: true
    velocity:
      graceticks: 20
      activationcounter: 80
      activationticks: 140
      strictinvalidation: true
    tempkickillegal: true
    loadchunks:
      join: true
    sprintinggrace: 2.0
    assumesprint: true
    speedgrace: 4.0
    enforcelocation: true
  net:
    flyingfrequency:
      active: true
      seconds: 5
      maxpackets: 300
    sounddistance:
      active: true
      maxdistance: 320
strings:
  angle: '[player] failed [check]: tried to hit multiple entities at the same time. VL [violations].'
  ban: ban [player]
  ban-ip: ban-ip [ip]
  bautosign: '[player] failed [check]: failed autosign with [tags]. VL [violations].'
  bbfrequency: '[player] failed [check]: tried to break too many blocks within time frame. VL [violations].'
  bdirection: '[player] failed [check]: tried to interact with a block out of their line of sight. VL [violations].'
  bedleave: '[player] failed [check]: sends bed leave packets (was not in bed). VL [violations].'
  bpspeed: '[player] failed [check]: tried to throw projectiles too quickly. VL [violations].'
  breach: '[player] failed [check]: exceeds block-interact distance ([reachdistance]). VL [violations].'
  bspeed: '[player] failed [check]: interacts too fast. VL [violations].'
  bvisible: '[player] failed [check]: interacts with a block out of sight. VL [violations].'
  bwrong: '[player] failed [check]: broke another block than clicked. VL [violations].'
  captcha: '[player] failed captcha repeatedly. VL [violations].'
  color: '[player] failed [check]: sent colored chat message. VL [violations].'
  commands: '[player] failed [check]: issued too many commands. VL [violations].'
  combspeed: '[player] failed [check]: performs different actions at very high speed. VL [violations].'
  critical: '[player] failed [check]: tried to do a critical hit but wasn''t technically jumping [tags]. VL [violations].'
  drop: '[player] failed [check]: tried to drop more items than allowed. VL [violations].'
  dropkick: ncp delay ncp kick [player] Dropping items too fast.
  fastbreak: '[player] failed [check]: tried to break blocks ([blockid]) faster than possible. VL [violations].'
  fastclick: '[player] failed [check]: tried to move items in their inventory too quickly. VL [violations].'
  fastconsume: '[player] failed [check]: consumes [food] [tags] too fast. VL [violations].'
  fastheal: '[player] failed [check]: regenerates health faster than usual. VL [violations].'
  fastplace: '[player] failed [check]: tried to place too many blocks. VL [violations].'
  fdirection: '[player] failed [check]: tried to hit an entity out of line of sight. VL [violations].'
  flyshort: '[player] failed [check]: tried to move unexpectedly. VL [violations].'
  flylong: '[player] failed [check]: tried to move from [locationfrom] to [locationto] over a distance of [distance] block(s). VL [violations].'
  freach: '[player] failed [check]: tried to attack entity out of reach. VL [violations].'
  fselfhit: '[player] failed [check]: tried to self-hit. VL [violations].'
  fspeed: '[player] failed [check]: tried to attack with too high a frequency. VL [violations].'
  chatnormal: '[player] failed [check]: potentially annoying chat. VL [violations].'
  godmode: '[player] failed [check]: avoided taking damage or lagging. VL [violations].'
  improbable: '[player] failed [check]: meets the improbable more than expected. VL [violations].'
  instantbow: '[player] failed [check]: fires bow too fast. VL [violations].'
  instanteat: '[player] failed [check]: eats food [food] too fast. VL [violations].'
  kick: kick [player]
  kickbedleave: ncp delay ncp kick [player] Go find a bed!
  kickbspeed: ncp kick [player] You interacted too fast!
  kickcaptcha: ncp kick [player] Enter the captcha!
  kickchat1: ncp tempkick [player] 1 You're still not allowed to spam!
  kickchat5: ncp tempkick [player] 5 You're not intended to spam!
  kickchatfast: ncp kick [player] You're not allowed to spam in chat!
  kickchatnormal: ncp kick [player] Too many chat messages, take a break.
  kickfly: ncp delay ncp kick [player] Kicked for flying (or related)
  kickcommands: ncp tempkick [player] 1 You're not allowed to spam commands!
  kickfrequency: ncp kick [player] You did something too fast!
  kickgod: ncp kick [player] God mode?
  kickpackets: ncp delay ncp kick [player] Too many packets (extreme lag?)
  kickselfhit: ncp kick [player] You tried to hit yourself!
  kickwb: ncp kick [player] Block breaking out of sync!
  knockback: '[player] failed [check]: tried to do a knockback but wasn''t technically sprinting. VL [violations].'
  morepackets: '[player] failed [check]: sent too many moves ([packets] [tags]). VL [violations].'
  munchhausen: '[player] failed [check]: almost made it off the pit. VL [violations].'
  nofall: '[player] failed [check]: tried to avoid fall damage. VL [violations].'
  chatfast: '[player] failed [check]: acted like spamming (IP: [ip]). VL [violations].'
  noswing: '[player] failed [check]: didn''t swing arm. VL [violations].'
  passable: '[player] failed [check]: moved into a block ([blockid]). VL [violations].'
  relog: '[player] failed [check]: relogs too fast. VL [violations].'
  tellchatnormal: 'ncp tell [player] &6AntiCheat: &eToo many messages, slow down...'
  tempkick1: ncp tempkick [player] 1 Wait a minute!
  tempkick5: ncp tempkick [player] 5 You have five minutes to think about it!
  anglenocancel: '[player] failed [check]: tried to hit multiple entities at the same time. VL [violations]. Not Canceled.'
  bbfrequencynocancel: '[player] failed [check]: tried to break too many blocks within time frame. VL [violations]. Not Canceled.'
  bdirectionnocancel: '[player] failed [check]: tried to interact with a block out of his line of sight. VL [violations]. Not Canceled.'
  bpspeednocancel: '[player] failed [check]: tried to throw projectiles too quickly. VL [violations]. Not Canceled.'
  breachnocancel: '[player] failed [check]: tried to interact with a block over distance [reachdistance] block(s). VL [violations]. Not Canceled.'
  bwrongnocancel: '[player] failed [check]: broke another block than clicked. VL [violations]. Not Canceled.'
  criticalnocancel: '[player] failed [check]: tried to do a critical hit but wasn''t technically jumping. VL [violations]. Not Cancele.d'
  fastbreaknocancel: '[player] failed [check]: tried to break blocks ([blockid]) faster than possible. VL [violations]. Not Canceled.'
  fastclicknocancel: '[player] failed [check]: tried to move items in his inventory too quickly. VL [violations]. Not Canceled.'
  fastplacenocancel: '[player] failed [check]: tried to place too many blocks. VL [violations]. Not Canceled.'
  fdirectionnocancel: '[player] failed [check]: tried to hit an entity out of line of sight. VL [violations]. Not Canceled.'
  flyshortnocancel: '[player] failed [check]: tried to move unexpectedly. VL [violations]. Not Canceled.'
  flyshortban: '[player] failed [check]: tried to move unexpectedly. VL [violations]. Player would have been banned.'
  flylongnocancel: '[player] failed [check]: tried to move from [locationfrom] to [locationto] over a distance of [distance] block(s). VL [violations]. Not Canceled.'
  freachnocancel: '[player] failed [check]: tried to attack entity out of reach. VL [violations]. Not Canceled.'
  fselfhitnocancel: '[player] failed [check]: tried to self-hit. VL [violations]. Not Canceled.'
  fspeednocancel: '[player] failed [check]: tried to attack with too high a frequency. VL [violations]. Not Canceled.'
  instantbownocancel: '[player] failed [check]: fires bow too fast. VL [violations]. Not Canceled.'
  instanteatnocancel: '[player] failed [check]: eats food [food] too fast. VL [violations]. Not Canceled.'
  sfsendmessage: ncp tell [player] &e&n Hey, it looks like you're glitching! Hold shift and right click with your sword a few times
  knockbacknocancel: '[player] failed [check]: tried to do a knockback but wasn''t technically sprinting. VL [violations]. Not Canceled.'
  morepacketsnocancel: '[player] failed [check]: sent [packets] more packet(s) than expected. VL [violations]. Not Canceled.'
  nofallnocancel: '[player] failed [check]: tried to avoid fall damage for ~[falldistance] block(s). VL [violations]. Not Canceled.'
  chatfastnocancel: '[player] failed [check]: acted like spamming (IP: [ip]). VL [violations]. Not Canceled.'
  noswingnocancel: '[player] failed [check]: didn''t swing arm. VL [violations]. Not Canceled.'
  warncommands: warn -a [player] Please do not spam commands!
  punishcommands: punish -a [player] You're not allowed to spam commands!
  warnchatfast: warn -a [player] Please do not spam in chat!
  punishchatfast: punish -a [player] You're not allowed to spam in chat!
  permachatfast: permaban -a [player] Severe chat spam is not tolerated.
  permaflyhacks: ban -a [player] Blatant flyhacks.
  warnchatnormal: warn -a [player] Too many messages, slow down...
  punishchatnormal: punish -a [player] Too many chat messages, please don't spam.
  bwrongkick: '[player] failed [check]: broke another block than clicked. VL [violations]. Player Kicked.'
compatibility:
  managelisteners: false
  bukkitapionly: false
  blocks:
    ignorepassable:
    - TRAP_DOOR
    - WOODEN_DOOR
    - IRON_DOOR_BLOCK
    - PISTON_EXTENSION
    - PISTON_MOVING_PIECE
    allowinstantbreak: []
    overrideflags:
      snow: default
